use std::fs;
use std::path::{Path, PathBuf};
use std::time::Duration;

use crate::stack::download::resolve_source;
use crate::stack::extract::{extract_zip, find_home_with_binary};
use crate::stack::process_util::{
    check_port_before_start_with_process, find_pid_by_port, is_pid_running, is_port_listening,
    kill_pid, path_forward, service_status, spawn_windows_background_with_env, tail_file,
    wait_for_port, wait_for_port_release,
};
use crate::stack::rabbitmq::deps::ensure_erlang_installed;
use crate::stack::store::{
    load_store, rabbitmq_conf_path, rabbitmq_config_file_base, require_install_root, save_store,
};
use crate::stack::types::RabbitMqInstall;

pub mod deps;
pub mod delayed_plugin;

const DEFAULT_MGMT_PORT: u16 = 15672;
const CLUSTER_PORT: u16 = 25672;
const START_TIMEOUT: Duration = Duration::from_secs(120);

pub fn install(
    source_path: Option<&str>,
    port: u16,
    version_name: &str,
    version_id: Option<&str>,
) -> Result<RabbitMqInstall, String> {
    let mut store = load_store();
    let install_root = require_install_root()?;
    let erlang_home = ensure_erlang_installed(&install_root)?;

    let source = resolve_source("rabbitmq", source_path, version_id)?;
    let base = install_root.join("rabbitmq").join("server");
    fs::create_dir_all(&base).map_err(|e| e.to_string())?;

    if source.is_file() {
        extract_zip(&source, &base)?;
    }
    let scan_root = if source.is_file() { &base } else { &source };
    let home_dir = find_rabbitmq_home(scan_root)?;

    let mgmt_port = DEFAULT_MGMT_PORT;
    let install = RabbitMqInstall {
        version_label: version_name.to_string(),
        home_dir: home_dir.to_string_lossy().into_owned(),
        erlang_home: erlang_home.to_string_lossy().into_owned(),
        port,
        mgmt_port,
        delayed_plugin: false,
        pid: None,
    };

    write_config(&install_root, &install)?;
    let home_path = Path::new(&home_dir);
    if delayed_plugin::is_version_supported(home_path, &install.version_label) {
        delayed_plugin::ensure_delayed_plugin(&install_root, home_path, &install.version_label)?;
    }
    let mut install = install;
    install.delayed_plugin = delayed_plugin::is_installed(home_path);
    write_enabled_plugins(&install_root, home_path)?;
    store.rabbitmq = Some(install.clone());
    save_store(&store)?;
    Ok(install)
}

fn find_rabbitmq_home(base: &Path) -> Result<PathBuf, String> {
    for rel in [
        &["sbin", "rabbitmq-server.bat"][..],
        &["rabbitmq-server.bat"][..],
    ] {
        if let Ok(home) = find_home_with_binary(base, rel) {
            return Ok(home);
        }
    }
    Err(format!(
        "未找到 rabbitmq-server.bat 于 {}",
        base.display()
    ))
}

pub fn write_config(install_root: &Path, install: &RabbitMqInstall) -> Result<(), String> {
    let conf_path = rabbitmq_conf_path(install_root);
    if let Some(parent) = conf_path.parent() {
        fs::create_dir_all(parent).map_err(|e| e.to_string())?;
    }
    let data_dir = install_root.join("rabbitmq").join("data");
    let log_dir = install_root.join("rabbitmq").join("logs");
    fs::create_dir_all(&data_dir).map_err(|e| e.to_string())?;
    fs::create_dir_all(&log_dir).map_err(|e| e.to_string())?;

    let conf = format!(
        r#"# Generated by dev-env
listeners.tcp.default = {port}
management.tcp.port = {mgmt_port}
default_user = guest
default_pass = guest
loopback_users.guest = false
default_vhost = /
log.file.level = info
log.dir = {log_dir}
"#,
        port = install.port,
        mgmt_port = install.mgmt_port,
        log_dir = path_forward(&log_dir),
    );
    fs::write(&conf_path, conf).map_err(|e| e.to_string())
}

pub fn uninstall() -> Result<(), String> {
    let mut store = load_store();
    if let Some(rabbitmq) = store.rabbitmq.take() {
        let _ = stop(&rabbitmq);
    }
    save_store(&store)
}

pub fn start() -> Result<RabbitMqInstall, String> {
    let mut store = load_store();
    let install = store
        .rabbitmq
        .as_ref()
        .ok_or("RabbitMQ 尚未安装")?
        .clone();

    let root = store.install_root.as_ref().ok_or("安装目录未设置")?;
    let install_root = Path::new(root);

    if is_fully_running(&install) {
        if let Some(running_pid) = find_pid_by_port(install.port) {
            if let Some(ref mut r) = store.rabbitmq {
                if r.pid.is_none() {
                    r.pid = Some(running_pid);
                    save_store(&store)?;
                }
            }
        }
        return Ok(install);
    }

    cleanup_stale_before_start(install_root, &install)?;

    if let Some(running_pid) = check_port_before_start_with_process(
        install.port,
        install.pid,
        "RabbitMQ",
        Some("erl.exe"),
    )? {
        if is_port_listening(install.mgmt_port) {
            if let Some(ref mut r) = store.rabbitmq {
                if r.pid.is_none() {
                    r.pid = Some(running_pid);
                    save_store(&store)?;
                }
            }
            return Ok(install);
        }
        force_stop_processes(&install);
        reset_mnesia_data(install_root)?;
    }

    let home = Path::new(&install.home_dir);
    write_config(install_root, &install)?;
    if delayed_plugin::is_version_supported(home, &install.version_label) {
        let _ = delayed_plugin::ensure_delayed_plugin_local(install_root, home, &install.version_label);
    }
    write_enabled_plugins(install_root, home)?;

    let sbin = home.join("sbin");
    let server_bat = sbin.join("rabbitmq-server.bat");
    if !server_bat.exists() {
        return Err(format!("未找到 rabbitmq-server.bat: {}", server_bat.display()));
    }

    let env = rabbitmq_env(install_root, &install);
    spawn_windows_background_with_env(&server_bat, Some(&sbin), &[], &env)?;

    if !wait_for_port(install.port, START_TIMEOUT) {
        cleanup_after_failed_boot(install_root, &install);
        let diag = diagnose_start_failure(&install, install_root);
        return Err(format!(
            "RabbitMQ 启动失败，AMQP 端口 {} 未监听（已自动清理残留进程并重置损坏的数据目录，请重试）。\n{diag}",
            install.port
        ));
    }

    if !wait_for_port(install.mgmt_port, Duration::from_secs(60)) {
        cleanup_after_failed_boot(install_root, &install);
        let diag = diagnose_start_failure(&install, install_root);
        return Err(format!(
            "RabbitMQ 管理界面端口 {} 未就绪（已自动清理，请重试）。\n{diag}",
            install.mgmt_port
        ));
    }

    let pid = find_pid_by_port(install.port);
    if let Some(ref mut r) = store.rabbitmq {
        r.pid = pid;
        r.delayed_plugin = delayed_plugin::is_installed(home);
        save_store(&store)?;
    }
    store.rabbitmq.clone().ok_or_else(|| "RabbitMQ 状态丢失".into())
}

pub fn stop(install: &RabbitMqInstall) -> Result<(), String> {
    let store = load_store();
    let root = store
        .install_root
        .as_ref()
        .ok_or("安装目录未设置")?;
    let install_root = Path::new(root);
    let home = Path::new(&install.home_dir);
    let ctl = home.join("sbin").join("rabbitmqctl.bat");
    // 仅当管理端口在监听时才尝试 rabbitmqctl，否则 ctl 可能无限等待 Erlang 节点
    if ctl.exists() && is_port_listening(install.mgmt_port) {
        let env = rabbitmq_env(install_root, install);
        let _ = run_command_in_with_env_timeout(
            &ctl,
            Some(&home.join("sbin")),
            &["stop"],
            &env,
            Duration::from_secs(15),
        );
        let _ = wait_for_port_release(install.port, Duration::from_secs(8));
    }
    force_stop_processes(install);
    let mut store = load_store();
    if let Some(ref mut r) = store.rabbitmq {
        r.pid = None;
        save_store(&store)?;
    }
    Ok(())
}

fn force_stop_processes(install: &RabbitMqInstall) {
    for port in [install.port, install.mgmt_port, CLUSTER_PORT] {
        if let Some(pid) = find_pid_by_port(port) {
            let _ = kill_pid(pid);
        }
    }
    if let Some(pid) = install.pid {
        let _ = kill_pid(pid);
    }
    let _ = wait_for_port_release(install.port, Duration::from_secs(5));
}

fn is_fully_running(install: &RabbitMqInstall) -> bool {
    is_port_listening(install.port) && is_port_listening(install.mgmt_port)
}

/// 启动前清理：杀掉卡在 boot 阶段的 orphan erl，并重置损坏的 mnesia。
fn cleanup_stale_before_start(install_root: &Path, install: &RabbitMqInstall) -> Result<(), String> {
    if is_fully_running(install) {
        return Ok(());
    }

    let mut killed_stale = false;
    if let Some((pid_path, pid)) = find_rabbitmq_pid_file(install_root) {
        if is_pid_running(pid) {
            let _ = kill_pid(pid);
            killed_stale = true;
        }
        let _ = fs::remove_file(&pid_path);
    }

    if !killed_stale {
        let cluster_busy = is_port_listening(CLUSTER_PORT) && !is_port_listening(install.port);
        if cluster_busy {
            force_stop_processes(install);
            killed_stale = true;
        }
    }

    if killed_stale {
        let _ = wait_for_port_release(CLUSTER_PORT, Duration::from_secs(8));
        reset_mnesia_data(install_root)?;
    }

    Ok(())
}

fn cleanup_after_failed_boot(install_root: &Path, install: &RabbitMqInstall) {
    if let Some((pid_path, pid)) = find_rabbitmq_pid_file(install_root) {
        if is_pid_running(pid) {
            let _ = kill_pid(pid);
        }
        let _ = fs::remove_file(&pid_path);
    }
    force_stop_processes(install);
    let _ = reset_mnesia_data(install_root);
}

fn find_rabbitmq_pid_file(install_root: &Path) -> Option<(PathBuf, u32)> {
    let data_dir = install_root.join("rabbitmq").join("data");
    let entries = fs::read_dir(&data_dir).ok()?;
    for entry in entries.flatten() {
        let name = entry.file_name();
        let name = name.to_string_lossy();
        if name.starts_with("rabbit@") && name.ends_with(".pid") {
            let pid = fs::read_to_string(entry.path()).ok()?.trim().parse().ok()?;
            return Some((entry.path(), pid));
        }
    }
    None
}

fn reset_mnesia_data(install_root: &Path) -> Result<(), String> {
    let data_dir = install_root.join("rabbitmq").join("data");
    if !data_dir.is_dir() {
        return Ok(());
    }
    for entry in fs::read_dir(&data_dir).map_err(|e| e.to_string())? {
        let entry = entry.map_err(|e| e.to_string())?;
        let path = entry.path();
        let name = entry.file_name().to_string_lossy().to_string();
        if name.ends_with("-mnesia") && path.is_dir() {
            fs::remove_dir_all(&path)
                .map_err(|e| format!("重置 RabbitMQ 数据目录失败: {e}"))?;
        } else if name.starts_with("rabbit@") && name.ends_with(".pid") {
            let _ = fs::remove_file(&path);
        }
    }
    Ok(())
}

pub fn stop_from_store() -> Result<RabbitMqInstall, String> {
    let install = load_store().rabbitmq.ok_or("RabbitMQ 尚未安装")?;
    stop(&install)?;
    load_store().rabbitmq.ok_or_else(|| "RabbitMQ 状态丢失".into())
}

pub fn status(install: &RabbitMqInstall) -> crate::stack::types::ServiceStatus {
    service_status(install.port, install.pid)
}

pub fn runtime_conf_path(install_root: &Path) -> PathBuf {
    rabbitmq_conf_path(install_root)
}

fn write_enabled_plugins(install_root: &Path, home_dir: &Path) -> Result<(), String> {
    let path = install_root.join("rabbitmq").join("enabled_plugins");
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|e| e.to_string())?;
    }
    let mut plugins = vec!["rabbitmq_management", "rabbitmq_management_agent"];
    if delayed_plugin::is_installed(home_dir) {
        plugins.push("rabbitmq_delayed_message_exchange");
    }
    let content = format!("[{}].\n", plugins.join(","));
    fs::write(&path, content).map_err(|e| format!("写入 enabled_plugins 失败: {e}"))
}

fn enabled_plugins_path(install_root: &Path) -> PathBuf {
    install_root.join("rabbitmq").join("enabled_plugins")
}

fn rabbitmq_env<'a>(install_root: &'a Path, install: &'a RabbitMqInstall) -> Vec<(&'a str, String)> {
    let base = install_root.join("rabbitmq");
    let config_base = rabbitmq_config_file_base(install_root);
    vec![
        ("ERLANG_HOME", install.erlang_home.clone()),
        ("RABBITMQ_HOME", install.home_dir.clone()),
        ("RABBITMQ_BASE", base.to_string_lossy().into_owned()),
        (
            "RABBITMQ_MNESIA_BASE",
            base.join("data").to_string_lossy().into_owned(),
        ),
        (
            "RABBITMQ_LOG_BASE",
            base.join("logs").to_string_lossy().into_owned(),
        ),
        (
            "RABBITMQ_CONFIG_FILE",
            config_base.to_string_lossy().into_owned(),
        ),
    ]
}

fn run_command_in_with_env_timeout(
    program: &Path,
    working_dir: Option<&Path>,
    args: &[&str],
    env: &[(&str, String)],
    timeout: Duration,
) -> Result<Option<std::process::Output>, String> {
    use std::process::{Command, Stdio};
    use std::sync::mpsc;
    use std::thread;

    let program = program.to_path_buf();
    let program_for_err = program.clone();
    let args: Vec<String> = args.iter().map(|s| s.to_string()).collect();
    let env: Vec<(String, String)> = env
        .iter()
        .map(|(k, v)| (k.to_string(), v.clone()))
        .collect();
    let working_dir = working_dir.map(|p| p.to_path_buf());

    let (tx, rx) = mpsc::channel();
    thread::spawn(move || {
        let mut cmd = Command::new(&program);
        cmd.args(&args)
            .stdout(Stdio::piped())
            .stderr(Stdio::piped());
        for (k, v) in &env {
            cmd.env(k, v);
        }
        if let Some(dir) = &working_dir {
            cmd.current_dir(dir);
        }
        #[cfg(windows)]
        {
            use std::os::windows::process::CommandExt;
            const CREATE_NO_WINDOW: u32 = 0x08000000;
            cmd.creation_flags(CREATE_NO_WINDOW);
        }
        let result = cmd
            .output()
            .map_err(|e| format!("执行 {} 失败: {e}", program.display()));
        let _ = tx.send(result);
    });

    match rx.recv_timeout(timeout) {
        Ok(result) => result.map(Some),
        Err(mpsc::RecvTimeoutError::Timeout) => Ok(None),
        Err(mpsc::RecvTimeoutError::Disconnected) => {
            Err(format!("执行 {} 异常中断", program_for_err.display()))
        }
    }
}

fn diagnose_start_failure(install: &RabbitMqInstall, install_root: &Path) -> String {
    let mut parts = vec![
        format!("ERLANG_HOME={}", install.erlang_home),
        format!(
            "配置文件: {}",
            rabbitmq_conf_path(install_root).display()
        ),
        format!(
            "插件配置: {}",
            enabled_plugins_path(install_root).display()
        ),
        format!(
            "管理界面: http://127.0.0.1:{}/ (guest/guest)",
            install.mgmt_port
        ),
        format!(
            "日志目录: {}",
            install_root.join("rabbitmq").join("logs").display()
        ),
    ];
    let erl = Path::new(&install.erlang_home).join("bin").join("erl.exe");
    if !erl.exists() {
        parts.push(format!("Erlang 未找到: {}", erl.display()));
    }
    if let Some(tail) = rabbitmq_log_tail(install_root) {
        parts.push(format!("最近日志:\n{tail}"));
    }
    parts.join("\n")
}

fn rabbitmq_log_tail(install_root: &Path) -> Option<String> {
    let log_dir = install_root.join("rabbitmq").join("logs");
    let entries = fs::read_dir(&log_dir).ok()?;
    for entry in entries.flatten() {
        let name = entry.file_name().to_string_lossy().to_string();
        if name.starts_with("rabbit@") && name.ends_with(".log") {
            return tail_file(&entry.path(), 8192);
        }
    }
    None
}
